%% -- FINGER DETECTION ALGORITHM -- %%
% -- THIS ALGORITHM DETECTS THE SKIN PIXELS FROM AN IMAGE -- %
tic
%% -- CLEARING MATLAB -- %%
clear all
clc
%% -- ALGORITHM 1: MAKES THE STUDY OF THE SKIN PIXELS GIVEN A TRAINING FOLDER WITH IMAGES AND MASKS -- %%
algo1
clc
%% -- ALGORITHM 6: CREATES THE BINARY IMAGES AND CALCULATES THE NUMBER OF FINGERS IN IT, STORES THE RESULTS ON TXT FILES -- %%
algo6
%% -- ALGORITHM 4 AND 7: CALCULATES THE FSCORE FOR THE VALIDATION IMAGES AND THE ERROR IN THE NUMBER OF FINGERS -- %%
algo4
algo7
toc